{{$CpuRequest := DefaultParam .CpuRequest "10m"}}
{{$MemoryRequest := DefaultParam .MemoryRequest "64M"}}
{{$Image := DefaultParam .Image "registry.k8s.io/pause:3.9"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: {{.Group}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: {{.Name}}
      group: {{.Group}}
  strategy:
    type: {{.DeploymentStrategy}}
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  template:
    metadata:
      labels:
        name: {{.Name}}
        group: {{.Group}}
    spec:
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "slo"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: pause
        image: {{$Image}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{$CpuRequest}}
            memory: {{$MemoryRequest}}